### ISSUE TITLE
MM-GAG data Unavailable

### ISSUE THREAD

**Issue by xianjiedai** [mvrl/GOMAA-Geo#1]
Hi,

Thanks for the awesome work and open source code!

The Hugging face link for the MM-GAG data is unavailable at the moment, i.e. https://huggingface.co/datasets/MVRL/MMGAG. Looking forward to seeing it available!

Thanks!

**Comment by xianjiedai** [comment]
Hi,

I also find some typo in train.py. Could you help me confirm them?

1.   line **115** of _train.py_ has_ one additional input arg "action"

`reward = ppo_agent.get_reward(cfg.data.patch_size, prev_patch_id, current_patch_id, goal_patch_id, seq.patch_sequence[1:-1], action, best_dist)`

2. line 263 of _models/ppo.py_ takes 3 positional args but 5 are provided:

`            logprobs, state_values, dist_entropy = self.policy.evaluate(old_states, old_actions, patch_sequence, patch_size)
`

**Comment by Vishu26** [comment]
Hi,

Thank you for your interest in our work. Thank you for pointing out the issues. We realised this was a development version of our repo. We have fixed the issues in the current version. We have also updated the dataset link!

Hope this helps!

**Comment by xianjiedai** [comment]
Thanks for the quick reply & update. I kept testing the code and there may be more typo:

3. Line 398 of _ppo.py_ has a redundent "action" input arg as well:

`                    reward = self.get_reward(cfg.data.patch_size, prev_patch_id, current_patch_id, goal_patch_id, seq.patch_sequence[1:-1], **action**, best_dist)
`

4. Line 147 of _train.py_ is comparing a tuple and an int:

`cur_val_success = ppo_agent.validate(config, cfg.data.val_path)
        if cur_val_success >= val_success:`

The return value(s) of `ppo_agent.validate()` is a tuple:

`return num_success, res`

Thanks!

**Comment by xianjiedai** [comment]
Hi again,

Will the GOMAA-Geo models be released soon? Looking forward to seeing them!

Thanks!

**Comment by Vishu26** [comment]
Hi
Yes, they will be released soon. 
Thank you!
